language: node_js
node_js: 11

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"
  - "echo airnimals.globaljake.com >> dist/CNAME"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
